language:   generic
sudo:   required
services:
    -   docker
before_install:
    -   docker build -t samarth/react -f Docker.dev .
script:
    -   docker run -e CI=true samarth/react npm run test -- --coverage